### ISSUE TITLE
Template Type Tests

### ISSUE THREAD

**Issue by DavePearce** [Whiley/Whiley2Boogie#18]
The following fails verification:

```
type nat is (int x) where x >= 0
type Box<T> is { T item }

function f(Box<nat> b) -> (nat r):
    return b.item
```

The problem is something to do with the type test for `Box<nat>`.  The problem is that the type test generated is agnostic to the type itself.  Therefore, we completely lose knowledge that `b.item` has type `nat`.  _One solution is to generate concrete type tests for each instantiation of a template_.  This is plausible at least.

**Comment by utting** [comment]
Can we treat template types as having parameters in the generated Boogie, so that the type test for Box actually takes two parameters: the 'type' T and the value?

We might do this by treating types as sets, or as predicates: (Any->bool).
Having type-valued input parameters at the Boogie level seems to correspond nicely to the kind of runtime type support that an implementation might do.
