### ISSUE TITLE
Mixing Side-Effects and Assertion Checks

### ISSUE THREAD

**Issue by DavePearce** [Whiley/Whiley2Boogie#71]
The following generates a precondition violation for reasons unknown:

```
type Reader is method()->int[]

public function apply(int[] data) -> int[]:
    return data

method main(Reader read):
    int[] input = apply(read())
```

It looks to be some kind of problem with lambda's?

**Comment by DavePearce** [comment]
This is to do with the ordering of side-effects versus assertion checks.  Specifically in this case we have the following:

```
   assert Test_Valid_1$apply$faIaI#pre(m);
   call HEAP, m := apply$mVaI(read,HEAP);
```
The problem is that `m` is not assigned until the second statement.

**Comment by DavePearce** [comment]
This problem is larger than I first thought, as illustrated by the following:

```
method m(int x) -> bool
requires x >= 0:
    return false

method main(int v):
    if v >= 0 && m(v):
        skip
```

The challenge is that we need to retain _window inference_ whilst extracting side-effects.  This is actually quite challenging.

**Comment by DavePearce** [comment]
Options:

1. Get rid of side-effects altogether.  _Is that even possible?_

**Comment by DavePearce** [comment]
Other suggestions:

- **(Post-Process)** Revert to HEAP as global variable. Then allow method calls in expressions. Then post process to eliminate them before final printing.

- **(Intermediate Language)** Have an intermediate language which has expression “blocks”. Like { x = y; x+1 }. The if is a unit block can translate directly. Otherwise need something else.

- **(Three-Address Code)**. Convert everything into three address code. Yuk!

**Comment by DavePearce** [comment]
Yet another option:

- Replace both `function` and `method` invocations with `procedure`s, and use `CALL`.  This offers some serious benefits if it can work (e.g. #21)

**Comment by DavePearce** [comment]
Here is one plan

1. Translate Expressions as Blocks.  That is a sequence of statements followed by an expression.
2. Translate Loops as Unstructured Control-Flow.  That is, using `if` and `goto` statements.

This kind of works, though I don't know how to address the use of function calls within specifications.

**Comment by utting** [comment]
The easiest solution would be to ban side-effects (hence method calls) within expressions.
But this might mean that a few existing programs (1%?  2%?) need to be restructured to avoid this.

Otherwise, I think the preprocessing approach looks promising.  It is easy to pull out method calls to just before the expression and assign the result to a temporary variable -- except in the case where that method call appears after a short-cut logical operator, such as the example above:  if v >= 0 && m(v): ...

I think this can be addressed by either:
1. expanding such short-cut operators into control flow logic, using rules like:
   if A || B: T else: F  ==>  if A: T else { if B: T else: F }
   if A && B: T else: F ==> if A: { if B: T else: F } else: F
   so that all method calls in any resulting expression *must* be called, so can be called before that expression.
or
2. moving the method call before the expression, but making its call conditional on the window inference context?
    E.g. translate:  if v >= 0 && m(v): ...
    to:   
        bool tmp = false;  // any default value
        if v >= 0: 
            tmp = m(v); 
        if v >= 0 && tmp: ...

**Comment by DavePearce** [comment]
Hey Mark,

It's good to discuss all this, since everything is up in the air at the moment.  For me to fully solve this issue, and a number of other issues (e.g. #21) I think some big changes are required.  It's frustrating since I need to change up the code more.

Let's start with this:

> The easiest solution would be to ban side-effects (hence method calls) within expressions.

Yes, that would be easiest solution by a landslide and that is what Dafny does.  But, in my opinion, it is absolutely the wrong solution (and the more I think on this, the more certain of it I become).  The whole point of a language like Whiley is to provide an _easy-to-use_ interface for verification.  We want the language to be driven by users, not by the underlying tools (e.g. Boogie in this case).

Fundamentally, there is no reason for disallowing method calls within expressions.  We know this, since there is a (relatively clear) translation in Boogie.  Furthermore, everyday programmers call methods from expressions all the time, and they will expect this.  See this [stack overflow question](https://stackoverflow.com/questions/34016762/dafny-call-methods-inside-if-statements) as just one example.

**Comment by DavePearce** [comment]
Right, second:

> Otherwise, I think the preprocessing approach looks promising

Yeah, I just cannot decide what is the best approach.  Your **option (2)** is one I am seriously considering.  But, in the end, I am wondering whether there is actually a solution where we don't pull method calls out at all.  We can treat them as uninterpreted functions as we do for Whiley `function`s.  The problem is that they modify the `HEAP` and we would need to thread this through.  I'm trying to think if I can make that work.  Hmmmmm, maybe but I don't know if it is worth it.

**Comment by DavePearce** [comment]
I should add that **option (2)** mandates that loops must now be translated using `goto` statements rather than Boogie's `While` statement.  This allows for method calls within loop conditions to be properly handled.  Potentially, you could use `While` in cases where there are no method calls in the condition.

**Comment by utting** [comment]
Let me play devil's advocate here for a moment. 
I think that concept of 'easy-to-use' is a bit ambiguous. 
Which do you mean:
    1. easy to verify?   (and sometimes a little harder to write)
    2. easy to write?   (and sometimes a little harder to verify)

I think the *answer* to that Dafny [stack overflow question](https://stackoverflow.com/questions/34016762/dafny-call-methods-inside-if-statements) was quite nice - just add one line of code to avoid the problems of side-effects, and perhaps make the code more readable.  That one line of code seems a small price to pay for making the verification rules (and the explanation of those rules) easy to understand.

Another reason I really like the idea of banning side-effects in expressions is readability - it means that everyone who reads Whiley code can automatically know that all expressions are pure, so never needs to think about the effects of the method calls in the expressions. 
Part of the problem here is that in Whiley like in Java/C etc., there is no syntactic difference between function calls and method calls, so when reading some new code, one has to treat *every* call as suspicious = possibly have side effects.  One could insist on having a warning keyword before any possibly-side-effecting call within expressions, like:
     if v >= 0 && **call** m(v): ...
This would warn readers about the (rare) calls that might have side-effects, and they would know that all other calls are safe.
But I think that always moving such side-effecting calls out into a separate statement makes the control-flow more explicit, and means that we get the global readability advantage of knowing that all expressions are pure.  This might allow more optimisation opportunities too.

**Comment by DavePearce** [comment]
Hey Mark,

> Which do you mean:
> 1. easy to verify? (and sometimes a little harder to write)
> 2. easy to write? (and sometimes a little harder to verify)

I think we should go with: _what will be familiar to everyday programmers_.  That is my goal: "verification for the masses"

> I think the answer to that Dafny stack overflow question was quite nice 

Right, but I thought it was horrific.  Think about it more.  What do we do when calling a method from a loop condition?  Also, how to we chain method calls together, like `x.m1().m2().m3()`.  Remember, we've going to be interoperating with objects from other languages (like Java) where there are a lot of methods.  Already I'm encountering this when representing the JavaScript DOM.  Somethings I can treat as pure, but other things I cannot.  The example above which started this thread arose from me writing code for a web application.  See my current [DOM model](https://github.com/Whiley/DOM.wy/blob/master/src/whiley/w3c/dom.whiley) to witness all the methods!

> it means that everyone who reads Whiley code can automatically know that all expressions are pure

Well, I get it and I'm more supportive of this.  For example, we could have a syntax like `m!()` for method calls (Rust uses this syntax for calling macros).  However, at the same time, I don't think it's necessary.  When calling a function or a method, to understand what it does you need to consult its spec.  It's just a given.  At least in Whiley, if you do this you'll see it's declared a `method` which immediately tells you it can have side effects.  Ideally, we have syntax which allows us to severely constrain those side-effects as well.

**Comment by DavePearce** [comment]
Closing this as subsumed by #74
