### ISSUE TITLE
Instant timeouts (Linux-specific?)

### ISSUE THREAD

**Issue by l-kent** [Whiley/Whiley2Boogie#91]
I'm experiencing timeouts occurring instantly when attempting to verify with Boogie. The following error occurs immediately when I run wy build, no matter what value of timeout I put, with only the 600s replaced by the value of timeout. 

Internal failure: java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: wybs.lang.SyntacticException: Boogie timeout after 600s

If timeout is set to be higher than the max integer value, then an error is returned for that instead. If no timeout value is set, a default value of 10 seems to be used, with the same result of the timeout error occurring instantly. 

I am using wyboogie 0.1.0, Ubuntu 20.04.2 LTS, Boogie version 2.8.26.0, and Z3 version 4.8.10. @utting found this did not happen on Windows, with the same files used, so it may be an operating system-specific issue. 

My wy.toml file is below.

```
[package]
name="conway"
authors=["David J. Pearce"]
version="0.1.0"

[build]
platforms=["whiley","js", "boogie"]

[build.whiley]
verify=false

[build.js]
target="public/js"

[build.boogie]
verify=true
timeout=600

[check]
min=-1
max=1
length=3
ignores=["main::draw"]

[dependencies]
dom="0.2.0"
```

**Comment by DavePearce** [comment]
Hey Liam,

Ok, let's get this sorted.  We need to narrow it down, ideally so I can recreate it.  Let's just begin with your installation process:

- **(WDK)** Which version have you started from?  I guess `wdk-v0.5.2`?  Did you confirm it works by, for example, running `wy` on its own (to see the help messages) and then perhaps `wy build` to make sure it generates a `wyil` file in the `bin/` directory?
- **(WyBoogie)** How did you install this?  Did you clone the repository `Whiley/Whiley2Boogie` and then run `ant` (if it wasn't already built using your IDE) and `ant plugin`?
- **(Global Config)** Did you edit the `wy.toml` file in the `wdk` installation directory?  It needs this line adding `wyboogie = "wyboogie.Activator"`

Unfortunately, a lot of the components have been updated since `wdk-v0.5.2`, and this maybe the cause.  I've been holding off making another big release until we'd got a good `wy2boogie` candidate to include.  This means you need to clone and manually install at least the following plugins:

1. `https://github.com/Whiley/WhileyCompilerCollection`
2. `https://github.com/Whiley/WhileyCompiler`
3. `https://github.com/Whiley/WhileyCommandLineInterface`

Potentially, I could actually just make another release which might help with the issue.  

One more thing you can try is: `wy --verbose build` which will give potentially a little more information about the problem.  You can report that here.

**Comment by l-kent** [comment]
I'm using wdk-v0.5.2. It works when `[build.boogie]` has `verify=false `and generates bpl, wyal, and wyil files in the bin directory. The generated bpl file can be used with boogie for verification, without any timeout issues. The Boogie timeout only happens when `[build.boogie] `has `verify=true`. 

I installed Whiley2Boogie by cloning the repository, building it with ant, and then copying wyboogie-0.1.0.jar from /target into the /lib folder of my wdk installation directory.

`wyboogie = "wyboogie.Activator" `is in my wdk installation directory's wy.toml file.

I had previously updated WhileyCompiler, but not WhileyCommandLineInterface or WhileyCompilerCollection. I have now updated them (both to 0.8.1, from 0.8.0), and this has made no difference.

When running wy --verbose build, I get the following, nearly immediately:

```
Downloaded https://github.com/Whiley/Repository/raw/master/index.txt ................ [0ms]
Loaded dom-v0.2.1 ................................................................... [0ms]
Loaded std-v0.3.1 ................................................................... [0ms]
Loaded js-v0.1.6 .................................................................... [0ms]
Internal failure: java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: wybs.lang.SyntacticException: Boogie timeout after 600s
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: wybs.lang.SyntacticException: Boogie timeout after 600s
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at wybs.util.SequentialBuildProject$1.get(SequentialBuildProject.java:199)
	at wybs.util.SequentialBuildProject$1.get(SequentialBuildProject.java:180)
	at wycli.commands.Build.execute(Build.java:138)
	at wycli.commands.Build.execute(Build.java:130)
	at wycli.util.AbstractWorkspace$1$1.execute(AbstractWorkspace.java:122)
	at wycli.WyMain.main(WyMain.java:162)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: wybs.lang.SyntacticException: Boogie timeout after 600s
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
	... 7 more
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: wybs.lang.SyntacticException: Boogie timeout after 600s
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1458)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.util.concurrent.ExecutionException: wybs.lang.SyntacticException: Boogie timeout after 600s
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at wybs.util.SequentialBuildProject.execute(SequentialBuildProject.java:243)
	at wybs.util.SequentialBuildProject.lambda$build$0(SequentialBuildProject.java:179)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1453)
	... 5 more
Caused by: wybs.lang.SyntacticException: Boogie timeout after 600s
	at wyboogie.tasks.BoogieCompileTask.execute(BoogieCompileTask.java:103)
	at wyboogie.tasks.BoogieCompileTask.lambda$initialise$0(BoogieCompileTask.java:78)
	at wybs.util.SequentialBuildProject.lambda$execute$1(SequentialBuildProject.java:242)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1453)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:396)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1004)
	... 8 more

```

**Comment by DavePearce** [comment]
Hey Liam,

Ok, a few things then.  Firstly, I have just put together a new release which updates to all the latest components and (for the first time) includes the Boogie plugin:

https://github.com/Whiley/WhileyDevelopmentKit/blob/master/dist/wdk-v0.5.3.tgz

_(at this stage, I don't think this will help you)_

I'm still guessing at what the problem is, but I think now it's to do with the benchmark specifically.  I'm not sure what @utting did getting it to verify.  He may have, for example, deleted all the files except the `model.whiley`.  I would suggest the following:

1. Create a simple repository which has these files:

*wy.toml*
```
[package]
name="main"
authors=["anon"]
version="0.1.0"

[build]
platforms=["whiley","boogie"]
``` 
*src/main.whiley*
```
public function abs(int x) -> (int r)
ensures r >= 0:
   return x
```
2. Try `wy build` on that project.  Hopefully it will produce an error saying the postcondition is violated.  Check the `.bpl` file was generated into the `bin/` directory

Make sure this all works first.  There are problems with timeouts relating to `method`s that I am aware of.  I haven't managed to fix them (because it's quite hard).  This might be the issue, then again it might not.

**Comment by l-kent** [comment]
I get
`Internal failure: java.lang.RuntimeException: java.util.concurrent.ExecutionException: wybs.lang.SyntacticException: Boogie timeout after 10s`
for that example. It still generates the bin/ directory (this is a detail I hadn't checked before) with the .bpl, .wyal, and .wyil files. 

Adding 
```
[build.boogie]
verify=false
```
to wy.toml prevents the timeout error from occurring here too.

**Comment by DavePearce** [comment]
Ok, that's bad!  Try running Boogie on the `bpl` file, like this:

`boogie bin/main.bpl`

And seeing what happens.  You are running on Windows is it?

Also try increasing the timeout to a large value for that simple example.

**Comment by DavePearce** [comment]
And in other news the github action now supports `Whiley2Boogie` !!  That means you can configure it to run whenever you push to a Whiley repository ...

**Comment by l-kent** [comment]
running boogie on the bpl file gives this
```
bin/main.bpl(193,4): Error: A postcondition might not hold on this return path.
bin/main.bpl(185,1): Related location: This is the postcondition that might not hold.
Execution trace:
    bin/main.bpl(190,9): anon0

Boogie program verifier finished with 0 verified, 1 error
```
which seems to be the expected result?

I'm using Ubuntu 20.04.2 LTS.

**Comment by DavePearce** [comment]
Yeah, that looks right.  I am also using Ubuntu 20.04.

Ok, I'll admit that it seems odd.  Let's change tack.  Try the newly release distribution `wdk-0.5.3`.  This should work out of the box.  For example, it is running correctly on the Github action which is Ubuntu 20.04 under-the-hood.  If that doesn't work ... then it's a slight mystery!

I am running `Boogie` version `2.7.43.0`.  You could also try running `boogie /timeLimit:10 bin/main.bpl` to see if that still works (since that's what the tool should be doing).

My best guess would be that the `wy` tool is not finding boogie somehow.  Did you run `boogie` in the same shell as where you are running `wy build` ?

**Comment by DavePearce** [comment]
For reference, here's the output from the build action:

https://github.com/Whiley/STD.wy/runs/2018770301?check_suite_focus=true

If you follow it down, you'll see that Boogie also times out (this is for the standard library which I haven't yet managed to verify with Boogie).  It's also running the quickcheck tool as well.

**Comment by l-kent** [comment]
wdk-0.5.3 doesn't make any difference.  Running `boogie /timeLimit:10 bin/main.bpl` performs the verification as expected. I have been running everything in the same shell. My Boogie version is the latest, v2.8.26.

**Comment by DavePearce** [comment]
Oh dear, well that is pretty frustating then.  We now have to debug the problem, which will be a bit of a pain.  Ah, there is one more thing to try which might help us.  Add this flag to the `wy.toml` file:

```
[build.boogie]
verbose=true
```

That should hopefully print some actual output from Boogie.  However, it could be an error message to the effect of "cannot find `boogie` command" or something.  Otherwise, the next step is to setup `Whiley2Boogie` in your IDE (Eclipse or IntelliJ?) and then add some debugging code into this file:

```
src/main/java/wyboogie/util/Boogie.java
```
In particular, we're interested in the contents of `stdout` and `stderr` after the `child` process has been run.  Is there any evidence that boogie is executing?

Ah, to drive the backend you can run the `ValidTests` which should (in theory) cause Boogie to run.

**Comment by l-kent** [comment]
```
[build.boogie]
verbose=true
```
makes no difference to the output.

I added code to `src/main/java/wyboogie/util/Boogie.java` to print stdout and stderr after the child process has been run, around line 132. stderr is empty but stdout is
`*** Error: '/nologo': Filename extension '' is not supported. Input files must be BoogiePL programs (.bpl).` 
when running the ValidTests. The ValidTests have the same timeout error as before.

**Comment by DavePearce** [comment]
Ok, that’s wierd. What Boogie version do you have? Try taking out the ‘/nologo’ parameter?

**Comment by DavePearce** [comment]
To do that, you could comment out this line:

```
command.add("/nologo");
```

But I definitely need to know what version of Boogie you have.  I did this to see:

```
% boogie anything
Boogie program verifier version 2.8.7.0, Copyright (c) 2003-2014, Microsoft.
```

**Comment by DavePearce** [comment]
Ok, yes, [version `2.8.15`](https://github.com/boogie-org/boogie/tags?after=v2.8.18) fixed this issue:

https://github.com/boogie-org/boogie/pull/316

Ugh!

**Comment by DavePearce** [comment]
Ok, simply commenting that parameter out seems to fix the problem.  It wasn't necessary and was there for legacy reasons.  I've also updated my version of Boogie to the latest, and updated `v0.5.3` to include this fix (since I hadn't publicised that release yet).

**Comment by DavePearce** [comment]
Ok, there are still some problems with the new version of Boogie, as error reporting is now broken ... grrr.

**Comment by DavePearce** [comment]
Ok, they also removed error codes in another issue:

https://github.com/boogie-org/boogie/pull/325
